// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmckzuvcbldhkewykikz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtY2t6dXZjYmxkaGtld3lraWt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNjA0NjksImV4cCI6MjA2NzkzNjQ2OX0.SYEF31zoZiPl3DO9ulTktFk20Zsg5gxYd7Yxel-BVvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});